[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
before-build = 'pip install numpy'
skip = ["cp310-macosx_x86_64", "pp*"]


[tool.cibuildwheel.linux]
before-all = "yum install -y openblas-devel lapack-devel libgomp || apk add openblas-dev lapack-dev libgomp"

[tool.cibuildwheel.macos]
# Run multiple commands using an array
before-all = [
  "brew install openblas",
  "brew install libomp",
]

[tool.cibuildwheel.windows]
# Run multiple commands using an array
before-all = [
  "powershell.exe Invoke-WebRequest https://github.com/xianyi/OpenBLAS/releases/download/v0.3.18/OpenBLAS-0.3.18-x86.zip -OutFile D:/a/cyanure/cyanure/openblas_86.zip",
  "powershell.exe Expand-Archive -Path D:/a/cyanure/cyanure/openblas_86.zip -DestinationPath D:/a/cyanure/cyanure/openblas_86",
  "powershell.exe Invoke-WebRequest https://github.com/xianyi/OpenBLAS/releases/download/v0.3.18/OpenBLAS-0.3.18-x64.zip -OutFile D:/a/cyanure/cyanure/openblas_64.zip",
  "powershell.exe Expand-Archive -Path D:/a/cyanure/cyanure/openblas_64.zip -DestinationPath D:/a/cyanure/cyanure/openblas_64",
]
before-build = "pip install delvewheel"
repair-wheel-command = "if \"%processor_architecture%\"  == \"AMD64\" (delvewheel repair -v --add-path=D:\\a\\cyanure\\cyanure\\openblas_64\\bin -w {dest_dir} {wheel}) else (delvewheel repair -v --add-path=D:\\a\\cyanure\\cyanure\\openblas_86\\bin -w {dest_dir} {wheel})"