[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
before-build = 'pip install numpy'
skip = ["cp310-macosx_x86_64", "pp*"]

[tool.cibuildwheel.linux]
before-all = "yum install -y openblas-devel lapack-devel libgomp || apk add openblas-dev lapack-dev libgomp"

[tool.cibuildwheel.macos]
# Run multiple commands using an array
before-all = [
  "brew install openblas",
  "brew install libomp",
]

[tool.cibuildwheel.windows]
# Run multiple commands using an array
before-all = [
  "certutil.exe -urlcache -split -f "https://github.com/xianyi/OpenBLAS/releases/download/v0.3.18/OpenBLAS-0.3.18-x64.zip" openblas.zip",
  "Expand-Archive -Path openblas.zip -DestinationPath C:\openblas";
]