[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
before-build = 'pip install numpy'

[tool.cibuildwheel.linux]
before-all = "yum install -y libffi-devel"