[build-system]
requires = [
    "setuptools",
    "wheel",
    "numpy==1.21.3"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
before-build = 'pip install numpy'
skip = ["cp310-*", "pp*"]

[tool.cibuildwheel.linux]
before-all = "yum install -y openblas-devel libgomp  || apk add openblas-dev libgomp"
test-command =  ["cd  {package}",]

[tool.cibuildwheel.macos]
# Run multiple commands using an array
before-all = [
  "brew install openblas",
  "brew install libomp",
]
test-command =  ["cd  {package}",]

[tool.cibuildwheel.windows]
# Run multiple commands using an array
before-all = [
  "powershell.exe Invoke-WebRequest https://github.com/xianyi/OpenBLAS/releases/download/v0.3.18/OpenBLAS-0.3.18-x86.zip -OutFile D:/a/cyanure/cyanure/openblas_86.zip",
  "powershell.exe Expand-Archive -Path D:/a/cyanure/cyanure/openblas_86.zip -DestinationPath D:/a/cyanure/cyanure/openblas_86",
  "powershell.exe Invoke-WebRequest https://github.com/xianyi/OpenBLAS/releases/download/v0.3.18/OpenBLAS-0.3.18-x64.zip -OutFile D:/a/cyanure/cyanure/openblas_64.zip",
  "powershell.exe Expand-Archive -Path D:/a/cyanure/cyanure/openblas_64.zip -DestinationPath D:/a/cyanure/cyanure/openblas_64",
]
before-build = "pip install delvewheel"
repair-wheel-command = "delvewheel repair -v --add-path=D:\\a\\cyanure\\cyanure\\openblas_64\\bin;D:\\a\\cyanure\\cyanure\\openblas_86\\bin\\ -w {dest_dir} {wheel}"
test-command =  ["cd /d {package}",]