# Install system library
[tool.cibuildwheel.linux]
before-all = "yum install -y openblas-devel lapack-devel"

[tool.cibuildwheel.macos]
# Run multiple commands using an array
before-all = [
  "brew install llvm",
  "brew install openblas",
  "brew install libomp",
]

[tool.cibuildwheel]
before-build = "pip install numpy"
