[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
before-build = 'pip install numpy'

[tool.cibuildwheel.linux]
before-all = "yum install -y openblas-devel lapack-devel"

[tool.cibuildwheel.macos]
# Run multiple commands using an array
before-all = [
  "brew install llvm",
  "brew install libomp",
]