[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
before-build = 'pip install numpy'
skip = [cp310-macosx_x86_64", "pp37-macosx_x86_64"]

[tool.cibuildwheel.linux]
before-all = "yum install -y openblas-devel lapack-devel"
manylinux-i686-image = "manylinux1"

[tool.cibuildwheel.macos]
# Run multiple commands using an array
before-all = [
  "brew install llvm",
  "brew install openblas",
]