name: Calculate code coverage

on: [push]

jobs:
  pytest_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install the package your testing.
        run: |
          export COVERAGE=1
          pip install .
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-cov
      - name: Remove conflicting folder
        run: |
          mv build/temp.linux-x86_64-3.9/cyanure_lib/cyanure_wrap_module.gcno cyanure_lib/
          mv build/temp.linux-x86_64-3.9/cyanure_lib/cyanure_wrap_module.gcda cyanure_lib/
          mv cyanure_lib cyanure_lib_tmp
      - name: Get coverage
        # fail_if_regression_in_coverage  
        run: |
          pytest --cov-config=.coveragec --cov=cyanure --cov-report xml:coverage.xml
          PYTHON_COVERAGE=$( xmllint --xpath 'string(/coverage/@line-rate)' coverage.xml)
          test=$(echo "$PYTHON_COVERAGE < 0.8" | bc)
          if ((test)); then echo "Failed because of python coverage";exit 1; fi


