name: Calculate code coverage

on: [push]

jobs:
  lint_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install the package your testing.
      run: |
        pip install .
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-cov
       - name: Remove conflicting folder
        run: |
          rm -rf cyanure_lib
      - name: Get coverage
        run: |
          pytest --cov-config=.coveragec --cov=cyanure