name: Calculate code coverage

on: [push]

jobs:
  pytest_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install the package your testing.
        run: |
          pip install .
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-cov
      - name: Remove conflicting folder
        run: |
          rm -rf cyanure_lib
      - name: Get coverage
        # fail_if_regression_in_coverage  
        run: |
          pytest --cov-config=.coveragec --cov=cyanure --cov-report xml:coverage.xml
          PYTHON_COVERAGE=$( xmllint --xpath 'string(/coverage/@line-rate)' coverage.xml)
          if (( $PYTHON_COVERAGE < 0.9 )); then exit 1; fi


