name: Sphinx build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    - name: Install the package your documenting together with its dependencies.
      run: |
        pip install .
    - name: Install the package your documenting together with its dependencies.
      run: |
        pip install -y sphinx, ipywidgets, beautifulsoup4, sphinx-rtd-theme, numpydoc, jupyter-sphinx, furo
    - name: Build the sphinx documentation and posts warnings as github comments.
      uses: rickstaa/sphinx-action@master
      with:
        docs-folder: "docs/sphinx/source"
        build-command: "sphinx-build -b html . _build"
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: html-docs
        path: docs/sphinx/source/_build/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/sphinx/source/_build/